default: &default
  adapter: postgresql
  pool: 5
  username: postgres

development:
  <<: *default
  database: unify_development

test: &test
  <<: *default
  database: unify_test

production:
  <<: *default
  database: unify_production
